name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    
    # Allow multiple Claude instances to work on different issues/PRs simultaneously
    concurrency:
      group: claude-${{ github.event.issue.number || github.event.pull_request.number || github.run_id }}
      cancel-in-progress: false
    
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating branches and pushing code
      pull-requests: write # Required for creating and updating PRs
      issues: write # Required for creating and updating issues
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history needed for complex git operations

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}" ]; then
            echo "CLAUDE_CODE_OAUTH_TOKEN is required"
            exit 1
          fi

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Optional: Allow Claude to run specific commands
          # Note: gh pr merge removed to prevent merging to main (use GitHub UI instead)
          allowed_tools: "Bash(pnpm install),Bash(npm install),Bash(pnpm lint),Bash(npm run lint),Bash(pnpm type-check),Bash(npm run type-check),Bash(pnpm test),Bash(npm test),Bash(pnpm build),Bash(npm run build),Bash(git status),Bash(git add),Bash(git commit),Bash(git push),Bash(git checkout),Bash(git branch),Bash(git diff),Bash(git log),Bash(git pull),Bash(gh pr create),Bash(gh pr list),Bash(gh pr view)"
          
          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            Follow the guidelines in CLAUDE.md
            Always run quality checks: pnpm lint && pnpm type-check && pnpm test && pnpm build
            If pnpm is not available, use npm equivalents: npm run lint && npm run type-check && npm test && npm run build
            Focus on TypeScript best practices and React component patterns
            When creating PRs: create descriptive branch names, write clear commit messages, and include proper PR descriptions
            For parallel work: use unique branch names to avoid conflicts
            Never commit changes unless all quality checks pass
            BRANCH PROTECTION: Never push directly to main branch. Always create feature branches and PRs.
            MERGE RESTRICTION: Only repository owner can merge PRs to main via GitHub UI - never use gh pr merge.
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

